# ===============================
# DEV CONFIG
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=tuyento1911

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.signerKey=ce6078d61114ce89a82b92a171419f492e53ae5561abcaf540e94603b6a48b54
jwt.valid-duration=3600
jwt.refresh-duration=36000
server.port=8080

vnpay.tmn-code=JNM5BKM2
vnpay.hash-secret=Z0OLXT4RHY3LCXAUZUE4BVZK5DI8HAHI
vnpay.base-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:3000/payment/return
vnpay.ipn-url=http://localhost:8080/payments/vnpay/ipn
vnpay.locale=vn
vnpay.order-type=other

# Redis Configuration
redis.enabled=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000
