# ===============================
# PROD CONFIG
# ===============================

spring.datasource.url=jdbc:postgresql://prod-server:5432/spring_boot_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=prod_user
spring.datasource.password=STRONG_PASSWORD

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.port=80
